source:          ./_source
destination:     ./_site
collections_dir: ./_source
plugins_dir:     ./_source/_plugins
layouts_dir:     ./_source/_layouts
data_dir:        ./_source/_data
includes_dir:    ./_source/_includes
collections:
  posts:
    output:   true
